import type { AppData, CampusConfig, User } from './types';

export const campusConfig: CampusConfig = {
  campuses: [
    {
      name: '三江校区东园',
      departments: [
        {
          name: '人工智能学部',
          colleges: [
            { name: '数理学院', majors: ['信息与计算科学', '应用数学'] },
            { name: '信息工程学院', majors: ['通信工程', '电子信息工程'] },
            { name: '低空技术学院', majors: ['无人机系统工程'] },
            { name: '电子信息产业学院', majors: ['集成电路设计与集成系统'] },
          ],
        },
      ],
    },
    {
      name: '三江校区西园',
      departments: [
        {
          name: '稀土与制造学部',
          colleges: [
            { name: '稀土学院', majors: ['稀土工程'] },
            { name: '材料科学与工程学院', majors: ['材料科学与工程', '新能源材料'] },
            { name: '电气工程与自动化学院', majors: ['电气工程及其自动化', '自动化'] },
          ],
        },
      ],
    },
    {
      name: '红旗校区',
      departments: [],
    },
  ],
};

export const currentUserSeed: User = {
  id: 'user_me',
  loginIdentifier: '拾遗用户A9K2',
  nickname: '拾遗用户A9K2',
  campus: '三江校区东园',
  department: '人工智能学部',
  college: '信息工程学院',
  major: '通信工程',
  role: 'user',
};

export const seedData: AppData = {
  users: [
    currentUserSeed,
    { id: 'seller_1', loginIdentifier: '林同学01', nickname: '林同学', campus: '三江校区东园', department: '人工智能学部', college: '信息工程学院', major: '通信工程', role: 'user' },
    { id: 'seller_2', loginIdentifier: '周同学02', nickname: '周同学', campus: '三江校区东园', department: '人工智能学部', college: '数理学院', major: '应用数学', role: 'user' },
    { id: 'seller_3', loginIdentifier: '何同学03', nickname: '何同学', campus: '三江校区西园', department: '稀土与制造学部', college: '稀土学院', major: '稀土工程', role: 'user' },
    { id: 'buyer_1', loginIdentifier: '许同学01', nickname: '许同学', role: 'user' },
    { id: 'buyer_2', loginIdentifier: '陈同学02', nickname: '陈同学', role: 'user' },
  ],
  books: [
    {
      id: 'book_csapp',
      sellerId: 'seller_1',
      title: '深入理解计算机系统',
      author: 'Randal E. Bryant',
      isbn: '9787111544937',
      category: 'textbook',
      images: [{ id: 'img_1', url: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=900&q=80', sortOrder: 0 }],
      priceCents: 3500,
      quantity: 1,
      condition: 'like_new',
      contact: 'wxid_csapp_2026',
      contactType: 'wechat',
      description: '第三版，封面轻微使用痕迹，前两章有铅笔笔记，适合计组和系统课程。',
      campus: '三江校区东园',
      department: '人工智能学部',
      college: '信息工程学院',
      major: '通信工程',
      status: 'available',
      createdAt: '2026-06-08T08:30:00.000Z',
      updatedAt: '2026-06-08T08:30:00.000Z',
    },
    {
      id: 'book_math',
      sellerId: 'seller_2',
      title: '高等数学 同济第七版 上下册',
      author: '同济大学数学系',
      isbn: '9787040396638',
      category: 'textbook',
      images: [{ id: 'img_2', url: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=900&q=80', sortOrder: 0 }],
      priceCents: 2800,
      quantity: 2,
      condition: 'annotated',
      contact: '13800001234',
      contactType: 'phone',
      description: '上下册一起出，有课堂重点标注，适合期末复习。',
      campus: '三江校区东园',
      department: '人工智能学部',
      college: '数理学院',
      major: '应用数学',
      status: 'available',
      lastMessageAt: '2026-06-08T09:20:00.000Z',
      createdAt: '2026-06-07T17:10:00.000Z',
      updatedAt: '2026-06-07T17:10:00.000Z',
    },
    {
      id: 'book_novel',
      sellerId: 'user_me',
      title: '百年孤独',
      author: '加西亚·马尔克斯',
      isbn: '9787544253994',
      category: 'novel',
      images: [{ id: 'img_3', url: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=900&q=80', sortOrder: 0 }],
      priceCents: 1800,
      quantity: 1,
      condition: 'worn',
      contact: 'wxid_my_books',
      contactType: 'wechat',
      description: '书页泛黄但不影响阅读，宿舍断舍离。',
      campus: '三江校区东园',
      department: '人工智能学部',
      college: '信息工程学院',
      major: '通信工程',
      status: 'available',
      lastMessageAt: '2026-06-08T10:10:00.000Z',
      createdAt: '2026-06-06T12:00:00.000Z',
      updatedAt: '2026-06-06T12:00:00.000Z',
    },
    {
      id: 'book_english',
      sellerId: 'seller_3',
      title: '六级真题逐句精解',
      author: '巨微英语',
      category: 'reference',
      images: [{ id: 'img_4', url: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&w=900&q=80', sortOrder: 0 }],
      priceCents: 2200,
      quantity: 1,
      condition: 'new',
      contact: 'wxid_cet6_book',
      contactType: 'wechat',
      description: '全新未拆，买多了一本。',
      campus: '三江校区西园',
      department: '稀土与制造学部',
      college: '稀土学院',
      major: '稀土工程',
      status: 'sold',
      buyerId: 'user_me',
      soldAt: '2026-06-08T09:40:00.000Z',
      createdAt: '2026-06-05T15:00:00.000Z',
      updatedAt: '2026-06-08T09:40:00.000Z',
    },
  ],
  interests: [
    { id: 'interest_1', bookId: 'book_math', buyerId: 'buyer_2', status: 'active', createdAt: '2026-06-08T09:00:00.000Z' },
    { id: 'interest_2', bookId: 'book_novel', buyerId: 'buyer_1', status: 'active', createdAt: '2026-06-08T10:05:00.000Z' },
    { id: 'interest_3', bookId: 'book_english', buyerId: 'user_me', status: 'chosen', createdAt: '2026-06-08T08:40:00.000Z' },
  ],
  messages: [
    { id: 'msg_1', bookId: 'book_math', fromUserId: 'buyer_2', content: '你好，高数上下册都在吗？', createdAt: '2026-06-08T09:18:00.000Z' },
    { id: 'msg_2', bookId: 'book_math', fromUserId: 'seller_2', content: '在的，可以今晚西园食堂门口交易。', createdAt: '2026-06-08T09:20:00.000Z' },
    { id: 'msg_3', bookId: 'book_novel', fromUserId: 'buyer_1', content: '书脊有没有破损？', createdAt: '2026-06-08T10:10:00.000Z' },
  ],
  evaluations: [
    { id: 'eval_1', bookId: 'book_english', fromUserId: 'user_me', toUserId: 'seller_3', fromRole: 'buyer', rating: 5, comment: '书是全新的，交易很顺利。', tags: ['书况如实', '沟通顺畅'], createdAt: '2026-06-08T11:00:00.000Z' },
  ],
  reports: [],
};
